### ISSUE TITLE
.intro-box not sizing correctly on different size screens

### ISSUE THREAD

**Issue by hummusonrails** [benhayehudi/pitgama#1]
The .intro-box is not sizing correctly when you view the site on anything below 1120px wide. It extends below the border of the .main-container. 

The CSS is located in `src/static_resources/stylesheets` and the styling for both .intro-box and .main-container are in `Main.css`.

**Comment by jokari** [comment]
#3  :/

**Comment by ahmadudin** [comment]
I recommend not to include `node_modules` folder on repository.

**Comment by hummusonrails** [comment]
Yes, good call! Thank you!

**Comment by hummusonrails** [comment]
Thanks @highkix for the fix for the overflow issue. Would you like to be listed as our first contributor on the README?

**Comment by jokari** [comment]
You're welcome! No need to add me on your README ;)
