### ISSUE TITLE
Issue with rendering <TextCard> on component

### ISSUE THREAD

**Issue by hummusonrails** [benhayehudi/pitgama#4]
Within `src/components/containers` is `Pitgama.js` which imports `TextCard` (found in `src/components/`) and supplies it with data to render individual cards from the information it receives from a `get` request to an external API. The data is being received and the `Redux` store is updating, but the `TextCard` is not rendering on `Pitgama.js`.

**Comment by NamanArora** [comment]
Let me try this one..

**Comment by hummusonrails** [comment]
All yours! 👍 
I'll be offline until Sunday, looking forward to checking out the PR then.
