### ISSUE TITLE
mobile responsiveness for About page

### ISSUE THREAD

**Issue by hummusonrails** [benhayehudi/pitgama#6]
The `About` component located in `src/components/containers` could use some help styling it to be mobile responsive. The CSS file is located in `src/static_resources/Main.css`. Specifically, centering the main body text after the first text box. Making sure the center image comes out correctly (i.e. not too blurry or overly stretched). That the headers for the two columns are aligned, and any other stylistic issues.

**Comment by Sergioamjr** [comment]
I'll do this ;)
